permissions:
    contents: write
    
name: build
on:
  push:
    tags:
      v*
  # schedule:
  #   - cron: "0 20 * * *" 
  workflow_dispatch:
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: compile
          uses: xu-cheng/latex-action@v3
          with: 
              root_file: main.tex
        - name: get date
          id: date
          run: echo "::set-output name=date::$(date +'%d.%m.%Y')"
        - name: release
          uses: softprops/action-gh-release@v2
          if: startsWith(github.ref, 'refs/tags/')
          with:
            make_latest: true
            files: main.pdf
        - name: prerelease
          uses: softprops/action-gh-release@v2
          if: ${{ !startsWith(github.ref, 'refs/tags/') }}
          with:
            tag_name: '${{ steps.date.outputs.date }}'
            prerelease: true
            files: main.pdf
